export const GET_LIST_WORKER_PENDING = "GET_LIST_WORKER_PENDING";
export const GET_LIST_WORKER_SUCCESS = "GET_LIST_WORKER_SUCCESS";
export const GET_LIST_WORKER_FAILED = "GET_LIST_WORKER_FAILED";

export const GET_LIST_RECRUITER_PENDING = "GET_LIST_RECRUITER_PENDING";
export const GET_LIST_RECRUITER_SUCCESS = "GET_LIST_RECRUITER_SUCCESS";
export const GET_LIST_RECRUITER_FAILED = "GET_LIST_RECRUITER_FAILED";

export const GET_DETAIL_USER_PENDING = "GET_DETAIL_USER_PENDING";
export const GET_DETAIL_USER_SUCCESS = "GET_DETAIL_USER_SUCCESS";
export const GET_DETAIL_USER_FAILED = "GET_DETAIL_USER_FAILED";
